name: Build & Publish Chrome Add-On

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm install

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Bump manifest.json version
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const m = JSON.parse(fs.readFileSync('manifest.json', 'utf8'));
          m.version = process.env.VERSION;
          fs.writeFileSync('manifest.json', JSON.stringify(m, null, 2));
          const p = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          p.version = process.env.VERSION;
          fs.writeFileSync('package.json', JSON.stringify(p, null, 2));
          NODE

      - name: Build signed XPI
        run: npm run build

      - name: Upload XPI to this release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            shyhurricane-chrome*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
